### ISSUE TITLE
лучше сделать отдельный экшен для сохранения коммента

### ISSUE THREAD

**Issue by paladinbbk** [PHPHillelYuriev/simple-blog#2]
https://github.com/PHPHillelYuriev/simple-blog/blob/51375b3c2b02f9283a45ca1279bd2853ff6f8627/src/Controller/MainController.php#L64

**Comment by PHPHillelYuriev** [comment]
Создал отдельный экшен, работает, но есть сомнения по поводу реализации в CommentManager
